version = 3
auto_upgrade = true
final_space = true

[palette]
  blue = '#70A8f8'
  grey = '#6C6C6C'
  lilac = '#AF7ABF'
  red = '#E05561'
  yellow = '#FCE77D'

[transient_prompt]
  template = '❯ '
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:lilac{{end}}']
  newline = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}'
    foreground = '#6C6C6C'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      cherry_pick_icon = '✓ '
      commit_icon = ' '
      fetch_status = true
      merge_icon = ' '
      no_commits_icon = '[no commits]'
      rebase_icon = 'Ɫ '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    foreground = 'p:yellow'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:lilac{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
