#!/bin/bash

DIR="$HOME/.config/sketchybar"
ITEM_DIR="$DIR/items"
PLUGIN_DIR="$DIR/plugins"

FONT="JetBrainsMono Nerd Font"
ICON_FONT="SF PRO"

PADDING=6

source "$DIR/colors.sh"
source "$DIR/icons.sh"

BAR_PROPS=(
  height=26
  color=$BG_PRI_COLR
  shadow=off
  position=top
  sticky=on
  padding_right=15
  padding_left=15
  corner_radius=10
  y_offset=8
  margin=10
  notch_width=200
)

DEF_PROPS=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:15.0"
  icon.padding_left=10
  icon.padding_right=2
  label.font="$FONT:Bold:14.0"
  label.color=$WHITE
  label.padding_left=$PADDING
  label.padding_right=10
  background.padding_left=$PADDING
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

# -- LEFT Side Items --
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/activity_monitor.sh"

# -- CENTRE Side Items --
# source "$ITEM_DIR/kaomoji.sh"
# source "$ITEM_DIR/spotify.sh"

# -- RIGHT Side Items --
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"


sketchybar --hotload on

sketchybar --update
